name: Generate SVG Contribution Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: gautam-droid
          outputs: |
            output/github-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push SVG to Output Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b output
          git add output/github-snake.svg
          git commit -m "Update SVG contribution snake"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
